version: '3.8'

services:
  client:
    build: ./client
    container_name: client
    ports:
      - "8080:8080"
    depends_on:
      - proxy

  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "8082:8082"
    depends_on:
      - server

  server:
    build: ./server
    container_name: server
    ports:
      - "8081:8081"
