version: '3.8'

services:
  client:
    build:
      context: ./client
    image: client:latest
    container_name: client-container
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - proxy

  proxy:
    build:
      context: ./proxy
    image: proxy:latest
    container_name: proxy-container
    ports:
      - "8082:8082"
    networks:
      - app-network
    depends_on:
      - server

  server:
    build:
      context: ./server
    image: server:latest
    container_name: server-container
    ports:
      - "8083:8083"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
