version: "3.8"
services:
  client:
    build:
      context: ./client
    ports:
      - "8081:8080"
    depends_on:
      - proxy

  proxy:
    build:
      context: ./proxy
    ports:
      - "8082:8080"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "8083:8080"
